######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 25 17:01:49 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
